### ISSUE TITLE
Frage bezüglich `defineIfNotDefined()`

### ISSUE THREAD

**Issue by leofeyer** [contao/symfony-todo#4]
@Toflar @discordier Warum habt ihr eigentlich die Methode `defineIfNotDefined()` implementiert? Soll das ein Workaround für den Fall sein, dass die `bootstrap.php` zweimal aufgerufen wird (einmal beim Container-Build und einmal beim Kernel-Boot)?

**Comment by aschempp** [comment]
> einmal beim Container-Build und einmal beim Kernel-Boot

Das kann nicht sein, da sie da ja eben nicht mehr vorkommt. Aber zum Beispiel bei einem Subrequest. Vielleicht sollte noch auf `isMasterRequest` getestet werden?

**Comment by Toflar** [comment]
Für Leute die eigene Entry-Scripts haben und da irgendwas definieren. Kein spezieller Grund - nur defensive Programming.

**Comment by leofeyer** [comment]
Das ist aber nicht nur defensive Programmierung sondern auch ein neues Feature, das ich eigentlich nicht unterstützen möchte. Jeder kann jetzt beliebig die Konstanten manipulieren.

**Comment by Toflar** [comment]
Meinetwegen können wir es auch weglassen, ausser @discordier findet noch einen anderen Grund.

**Comment by aschempp** [comment]
Aus meiner Sicht ändert sich dadurch nichts. Keiner kann die Konstanten manipulieren. Es ist einfach als ob du erst ein `isset` auf die Variablen machen würdest…

**Comment by leofeyer** [comment]
> Keiner kann die Konstanten manipulieren

Doch klar. Eigener Entry-Point, dort definiere ich `TL_ROOT` und was ich sonst noch so möchte. Bisher gab das eine Fehlermeldung, jetzt würde es gehen.

**Comment by aschempp** [comment]
It will raise a PHP notice, which is basically ignored if you have a production system.

**Comment by discordier** [comment]
Das ist primaer drin, damit unit tests u.a. die Konstanten selber definieren koennen. Ansonsten schlagen die immer fehl von wegen dass sie schon definiert sind.

Da die ganzen includes sich auch noch gegenseitig included haben, konnte man bislang nicht einmal sagen "ok, dann lass ich die constants eben weg".
Um diese Probleme (die ich seit Contao 2.X Zeiten habe) zu vermeiden, habe ich mich fyr diese Methode entschieden gehabt.

Ich moechte nochmals unterstreichen, dass wir diese Konstanten allgemein nicht mehr verwenden sollten!

**Comment by discordier** [comment]
Ich weiss noch einen validen Grund, den wir zwar bereits kurz besprochen haben, der aktuell mangels Implementierung noch nicht funktioniert.

Die von @Toflar und mir angedachte Implementierung sieht vor die SAPI auszuwerten und wenn wir eine Web SAPI haben, dann entsprechend unseren listener "von Hand" zu triggern, damit alles sauber gesetzt wurde, wenn wir eine CLI SAPI haben, dann entsprechend den `console.command` event handler triggern.

Wenn die Konstanten in diesem Falle immer gesetzt wyrden, dann triggert dies etliche Warnings obwohl die eigentlich nicht noetig waeren.

Wenn jemand die `initialize.php` selbst inkludiert und anschliessend den Kernel verwendet um einen request zu behandeln (auf welchem Wege auch immer), dann wyrde das Event `kernel.request` getriggert werden. Der zweite Fall, dass man nach einem include der `initialize.php` eine console application executed ist weit unwahrscheinlicher jedoch theorethisch auch denkbar.

Um das jedoch allgemein zu ermoeglichen myssen wir bei den functions und mb_string die jeweiligen Funktionen noch sauber mit `if (!function_exists('foo')) {}` wrappen.

**Comment by aschempp** [comment]
> Der zweite Fall, dass man nach einem include der initialize.php eine console application executed ist weit unwahrscheinlicher jedoch theorethisch auch denkbar.

Das würde bei jedem passieren welcher den CronJob auf der Kommandozeile aufruft oder?

**Comment by discordier** [comment]
Nein, ich rede hier von "echten" Symfony Console Applications, welche die `initialize.php` zur `__construct()` Zeit includen.
@tristanlins hatte sowas AFAIR mal gebaut.

**Comment by aschempp** [comment]
Das dürfte wirklich nicht vorkommen… aber bei meinem Beispiel wär die SAPI natürlich auch CLI.

**Comment by discordier** [comment]
Ja, aber der Code wyrde nicht zweimal executed.

1. Aus `initialize.php` via unserer Implementierung.
2. aus `Application::run()` via Event `console.command`.

In deinem Beispiel waere nur 1. aktiv, in einer echten Application sowohl 1. als auch 2.
