### ISSUE TITLE
Contao als Symfony-App oder als Symfony-Bundle

### ISSUE THREAD

**Issue by leofeyer** [contao/symfony-todo#5]
Ich habe (wie alle von euch vermutlich) über unser Gespräch von heute Nachmittag nachgedacht und mir gefällt der Gedanke, dass Contao "nur" eine Symfony-Bundle-Collection ist, mit dem man CMS-Funktionalität bei Bedarf zu einer Symfony-App hinzufügt.

Außerdem hatte ich die Idee, dass wir zwei Distributionen anbieten könnten: eine mit und eine ohne Legacy-Environment.

Weiterhin kam mir der Gedanke, dass jemand, der seine Distribution anpassen will, ja im Grunde eine eigene Distribution erstellt. Das Live-Update könnte also prüfen, ob eine der Standard-Distributionen verwendet wird und diese nur dann anpassen (nämlich wenn der Composer-Name entweder `contao/contao` oder `contao/contao-with-legacy` ist).

Die Composer-Paketverwaltung könnte dann prüfen, ob die `contao/contao-with-legacy`-Distribution verwendet wird und falls nicht die Installation von Contao 3-Extensions verweigern.

Soweit meine Gedanken dazu :)

**Comment by leofeyer** [comment]
Ach so, Contao wäre dann das Core-Bundle und dessen Versionsnummer würden wir anzeigen. Die Distribution hätte keine eigene Version mehr, weil es ja quasi nur noch ein "Runtime Environment" wäre.

**Comment by aschempp** [comment]
Gefällt! Allerdings hab ich Yanick diskutiert und wir sind uns nicht sicher ob Composer eine Abhängigkeit zur Distribution auflösen kann? Also eine Version in seiner eigenen composer.json prüft?

**Comment by leofeyer** [comment]
> ob Composer eine Abhängigkeit zur Distribution auflösen kann

Was meinst Du damit?

**Comment by Toflar** [comment]
Er meint, dass ich in meinem Bundle `terminal42/any-contao-bundle` sagen kann, ich passe nur zur Version `4.*` der Distribution `contao/contao`. Dann könnte nämlich gar niemand die neuen Versionen des Core Bundles etc. holen, wenn die Distribution - oder "Runtime Environment" - nicht passt.

**Comment by Toflar** [comment]
Das Problem mit den zwei Distributionen ist folgendes: Die Dependency ist am falschen Ort. Mein `xy`-Bundle entscheidet ja ob es das Legacy-Environment braucht oder nicht :)

**Comment by aschempp** [comment]
Jein, wenn du Legacy-Module verwenden willst, musst du die Legacy-Distribution nehmen. Die Frage ist ob Composer das prüfen kann (z.B. mit "type: contao-module" und "type: contao-bundle").

**Comment by Toflar** [comment]
Ja, versteh ich schon aber das `core-bundle` selber braucht ja die Legacy-Distribution. Und überhaupt, was ausser einem angepassten AppKernel würde denn die nicht-legacy-Distribution im Vergleich zur SF2 Standard-Edition mitbringen? :D

**Comment by aschempp** [comment]
Die Standard-Distribution hätte keine Assets und kein system/initialize.php etc.

**Comment by Toflar** [comment]
Hä? Lies richtig :) Ich hab gefragt was die NICHT-legacy im Vergleich zur SF2 Distribution bieten würde. Da brauchts ja weder Assets noch system etc.

**Comment by aschempp** [comment]
Ach soo, sorry :D
Ich denke sie würde Dinge wie Bundle-Autoloading und Bundle-Routen standardmässig aktivieren. Und natürlich unsere Empfehlungen der Abhängigkeiten in der composer.json (z.B. WebProfilerBundle).

**Comment by Toflar** [comment]
Hmm..okay...aber das käme ja erst dann in Frage wenn das `core-bundle` selbst nix mehr vom Legacy-Zeugs braucht und da wir wenn möglich BC halten wollen in der 4 ist das erst mal gar kein Thema - aber in der Zukunft vielleicht, ja :)

**Comment by leofeyer** [comment]
Vor allem geht es darum, das Core-Bundle unabhängig von der Distribution zu halten. Dann kann ich selbst entscheiden, ob ich die Symfony-Standard-Edition, die CMF-Standard-Edition, die Rest-Standard-Edition, die Contao-Standard-Edition oder eine eigene Distribution verwenden will.

Das `terminal42/any-contao-bundle` würde dann auch nur sagen, zu welcher Version von `contao/core-bundle` es passt. Die Distribution wäre vollkommen egal.

**Comment by leofeyer** [comment]
Aber - und es war ja klar, dass ein Aber kommt: Die Distribution sollte dann auch komplett vorkonfiguriert sein, so wie es bei den bestehenden Editionen der Fall ist:

- https://github.com/symfony/symfony-standard
- https://github.com/symfony-cmf/standard-edition
- https://github.com/gimler/symfony-rest-edition

Das ganze Prepend-Zeug finde ich falsch.

**Comment by Toflar** [comment]
> Das ganze Prepend-Zeug finde ich falsch.

Oder eine geniale Idee, auf die die anderen noch nicht gekommen sind :D

**Comment by aschempp** [comment]
> Das ganze Prepend-Zeug finde ich falsch.

Es ist nicht falsch, aber komisch. Ich sehe lediglich das Problem, dass die Distribution nicht entscheiden kann wie die Config ist bzw. ob die ContaoCore-Defaults geladen werden sollen. Mit `@import` ginge das, aber dann haben wir wie besprochen das Problem der ev-nicht-vorhandenen Bundles.

**Comment by leofeyer** [comment]
Wir müssen das einfach nochmal besprechen. Im Ticket diskutieren ist zäh in diesem Fall.

**Comment by leofeyer** [comment]
Hier mal ein Beispiel für eine Upgrade-Anleitung: https://gist.github.com/nicwortel/0c938aa77c5bd4fde064

**Comment by leofeyer** [comment]
Weitere Gedanken: Jedes Bundle sollte seine Konfigurationsdateien als `.yml`-Dateien bereitstellen. Diese Konfigurationsdateien können dann in `app/*.yml` mittels `include` eingebunden werden. Alternativ kann auch eine eigene Konfiguration hinterlegt werden.

In diesem Zug würde ich auf das ganze Prepend-Zeug verzichten und sogar das Bundle-Autoloading wieder rausschmeißen. Stattdessen sollten wir uns lieber eine gute Möglichkeit überlegen, wie Anwender die Konfigurationsdateien in `app/config` und den App-Kernel anpassen können. Eventuell über einen Editor im Backend, der die Einstellungen anhand der [Symfony Definitions](http://symfony.com/doc/current/components/config/definition.html) prüft?

**Comment by leofeyer** [comment]
Ich würde dann sogar soweit gehen und das jetzige Core-Bundle unter `contao/contao` pflegen. Die Distributionen lägen dann unter `contao/standard-edition` und `contao/legacy-edition`.

**Comment by Toflar** [comment]
Die Definitions habe ich mir schon angesehen. Chris weiss das auch schon. Siehe auch https://github.com/symfony/symfony/issues/13456

**Comment by leofeyer** [comment]
Korrektur meiner Gedanken: Ich würde `contao/core-bundle` doch belassen und `contao/contao` als "Meta-Bundle" aufbauen:

```json
{
    "name": "contao/contao",
    "require": {
        …
    },
    "replace": {
        "contao/calendar-bundle": "self.version",
        "contao/comments-bundle": "self.version",
        "contao/core-bundle": "self.version",
        "contao/faq-bundle": "self.version",
        "contao/listing-bundle": "self.version",
        "contao/news-bundle": "self.version",
        "contao/newsletter-bundle": "self.version"
    },
    …
}
```

Die beiden Editionen `contao/standard-edition` und `contao/legacy-edition` würde ich aber beibehalten.

**Comment by aschempp** [comment]
Gerade festgestellt, wir sollten auch die `dcaconfig.php` und `langconfig.php` deprecaten, die Leute sollten ein AppBundle nutzen.

**Comment by leofeyer** [comment]
Noch ein Gedanke hierzu: Am besten wäre es wohl, wenn das Core-Bundle ein Composer `post-install-cmd` enthält, das die benötigten Ressourcen automatisch erstellt bzw. symlinkt. Oder ein Konsolen-Befehl so wie `assets:install` dann eben `contao:setup`. Ich denke nämlich nicht, dass wir ad hoc ohne `/files`, `/system/config`, '/system/tmp` und `/templates` auskommen.

**Comment by leofeyer** [comment]
Die Installationsanleitung für Contao würde dann wie folgt aussehen:

Füge Deiner `composer.json` folgendes hinzu:

```json
{
    "require": {
        "contao/contao": "~4.0"
    },
    "config": {
        "component-dir": "web/assets"
    },
    "post-install-cmd": {
        "php app/console contao:setup"
    },
    "post-update-cmd": {
        "php app/console contao:setup"
    }
}
```

Beim `composer update` würden dann alle Contao-Repos installiert und `contao:setup` würde alle benötigten Ordner anlegen, wenn diese noch nicht existieren:

- `/files`
- `/system/config`
- `/system/modules`
- `/system/themes`
- `/system/tmp`
- `/system/initialize.php`
- `/templates`
- `/web/share`

Die einzige noch offene Frage ist wie wir die Config-Dateien nach `/system/config` bekommen. Selbst wenn wir sagten, dass diese zukünftig in `app/config` liegen sollen, müssen sie irgendwie angelegt werden. Ideen?

**Comment by Toflar** [comment]
Ist es utopisch alle Core-Configs neu via `parameters.yml` zu managen und einfach nur sicherzustellen, dass die 4 customs (`localconfig.php`, `dcaconfig.php`, 'initconfig.php` und `langconfig.php`) berücksichtigt werden? Dann müssen wir nix anlegen :)

**Comment by leofeyer** [comment]
Ja, das ist ziemlich utopisch. Gerade die RTE-Configs werden viel angepasst und lassen sich nur schlecht als `.yml`-Dateien verwalten.

**Comment by leofeyer** [comment]
Ich hab die Lösung: Wir machen Templates aus den Config-Dateien. Dann gibt es auch kein Problem mehr mit der updatesicheren Anpassung. (Sollten wir für die 3.5 eigentlich auch gleich ändern.)

**Comment by aschempp** [comment]
Templates?

**Comment by leofeyer** [comment]
Ja. `be_ace.html5`, `be_tinyMCE.html5` usw. Die kann man dann einfach mittels Template-Editor überschreiben. (Sind ja jetzt auch eigentlich Templates.)

**Comment by leofeyer** [comment]
Was jetzt noch übrig ist, sind folgende Magic-Features:

 * `files/tinymce.css`
 * `files/tiny_templates`

@contao/developers Kann das weg? Kann man sich ja bei Bedarf im TinyMCE-Template wieder aktivieren.

**Comment by discordier** [comment]
Hab ich nie verwendet.
Da wir aber Major sind, kann das entfallen. Besonders wenn man es sich wieder konfigurieren kann.
Schmeiss raus.

**Comment by Toflar** [comment]
Dito :)

**Comment by aschempp** [comment]
Benutze ich auch nie, aber nicht-Entwickler wie @frontendschlampe nutzen das oft.

**Comment by leofeyer** [comment]
Die können das in Contao 4 aber viel einfacher updatesicher konfigurieren, weil die Konfigurationsdateien ja jetzt echte Templates sind. Und die ganzen Methoden wie z.B. `Backend::getTinyTemplates()` etc. habe ich drin gelassen.
