### ISSUE TITLE
Central repository with subtree splits vs multiple separate repositories

### ISSUE THREAD

**Issue by leofeyer** [contao/symfony-todo#6]
## What's it all about

As discussed yesterday, we may want to make `contao/contao` one big central repository containing all bundles so it is easier to create pull requests and references in tickets.

```
vendor/
  contao/
    contao/
      src/
        CalendarBundle
        CommentsBundle
        CoreBundle
        …
```

We would then use subtree splits to create the separate repositories, much like Guzzle or Symfony do it.

## Required changes

We would not longer be able to have subfolders such as `contao/` or `tests/`, so the resources would have to be moved:

```
vendor/
  contao/
    contao/
      src/
        CoreBundle
          src/
            Command/
            Controller/
            Resources/
              config/
              contao/    <---- the contao/ folder goes here
            Tests/       <---- the tests/ folder goes here
```

## Pros and cons

| # | Pro  | Con
| --- | --- | ----
| 1 | One repo contains the code and the tickets | Maintaining the change logs and `composer.json` files is more work
| 2 | Everything can easily be referenced and pull requests can span multiple repos | Pull requests can not be told apart easily anymore, tickets have to be read in detail to know what repository they are related to (unless having a whole load of tags)
| 3 | Creating the subtree splits can be automated with existing and tested scripts | Sub tree splits get expensive over time with increasing commit count
| 4 | | The core will get bloated with additional modules/bundles (news, newsletter, ...) again which are not part of the "Framework" which was the main reason to strip them out.
| 5 | | Unit tests will get harder to maintain when interfacing with legacy code as there can only be one `bootstrap.php` defined in `phpunit.xml.dist` which will then have to keep track of it's current location and has to be copied/synchronized across all repositories

## Alternative

The alternativ would be to keep the repositories separate. The biggest problem then is where to create the tickets. We would probably have to enable issues in all repositories with `contao/core-bundle` being the main one. However, this is not intuitive for the users and will lead to misplaced tickets.

## Current votes

@discordier -1
@aschempp +1
@Toflar [both are shit, but I tend to -1]
@leofeyer -1

**Comment by discordier** [comment]
I have updated the table with some mote contra points.
Feel free to discuss.

I want to stress the discussion on Con.4 again.
IMO the modules that we shipped should not be maintained together with the core but only be shipped with the standard edition.

If you need prominent examples from symfony that are not maintained within the [symfony/symfony](https://github.com/symfony/symfony) repository:
* [symfony/assetic-bundle](https://github.com/symfony/AsseticBundle) required by [symfony/symfony-standard](https://github.com/symfony/symfony-standard/blob/2.7/composer.json#L16)
* [symfony/SwiftmailerBundle](https://github.com/symfony/SwiftmailerBundle) required by [symfony/symfony-standard](https://github.com/symfony/symfony-standard/blob/2.7/composer.json#L17)
* [symfony/MonologBundle](https://github.com/symfony/MonologBundle) required by [symfony/symfony-standard](https://github.com/symfony/symfony-standard/blob/2.7/composer.json#L18)

All of these are additional stuff that is not needed for many projects. Especially the assetic bundle is a very good example.
To put it in Contao context, it means to have "FAQ" back in the core repository and maintain it within there despite the fact that not even ~10% of all Contao sites are using it in production (rough estimate by me - I have only used it 2 or 3 times in the whole past).
Same for the listing-bundle which I have used seldomly as well.
The news I have used more often but I still argue that we will need it in the same repository.

My main point is, the framework repository (contao/contao) should not be polluted with "application code" performing "real" generating of output and providing additional elements.

We can not compare this to symfony directly as in there nothing like the Contao modules/extensions exists. The most closely reensembling thing in there is only the debug bundle, which is even only a sub routine in legacy contao. Everything else is simply library code which can be used standalone (along with it's base dependencies).

**Comment by leofeyer** [comment]
If we keep things as is, we also have to enable issues in every repository. Right now we are having all issues in `contao/contao` and all the code somewhere else :)

**Comment by Toflar** [comment]
> IMO the modules that we shipped should not be maintained together with the core but only be shipped with the standard edition.

:+1:

**Comment by aschempp** [comment]
If, and ONLY IF, the modules are actually developed separately and do get their own version number etc, then it would make sense to keep them separate. But then we should also investigate if they are somewhat related to each other and get rid of that.

For example, the insert tags for news items are currently replaced in the controller (https://github.com/contao/core-bundle/blob/149390581f989d68a270bc8f408c4b246a4dec0a/contao/library/Contao/InsertTags.php#L497) and the model class provides a lot of `@method` for third-party modules (https://github.com/contao/core-bundle/blob/149390581f989d68a270bc8f408c4b246a4dec0a/contao/models/UserModel.php#L107).

**Comment by leofeyer** [comment]
Another thing: Even if we decide to keep the modules separate, I'd love to integrate the tests in `src/Tests/` and the Contao resources in `Resources/contao/`. Then we would not have to add a compiler path to set the contao resources path, because it would always be `Resources/contao/`. Any objections?

**Comment by aschempp** [comment]
I agree with `Resources/contao` but I'm not sure about the tests. Someone somewhen said something about Symfony only does it that way because there's no other option, but not because it's good practice.

**Comment by Toflar** [comment]
> Any objections?

Yes, it's ugly. I prefer `tests` over `src/Tests/` and `contao` over `Resources/contao/` :)

**Comment by leofeyer** [comment]
> Someone somewhen said something about

Please let us not build our decisions upon strong arguments such as "someone somewhen said something"!

**Comment by leofeyer** [comment]
Here's the official Symfony recommendation for the bundle structure:

http://symfony.com/doc/current/cookbook/bundles/best_practices.html#directory-structure

```
XXX/...
    HelloBundle/
        HelloBundle.php
        Controller/
        Resources/
            meta/
                LICENSE
            config/
            doc/
                index.rst
            translations/
            views/
            public/
        Tests/
```

Please take a look at where the `Tests` folder is :)

**Comment by Toflar** [comment]
Obviously that's their recommendation because they cannot do it the other way around :D They would be recommending something they cannot satisfy themselves otherwise :D Not everything they recommend has to be right :)

**Comment by leofeyer** [comment]
Yes, but since we are using Symfony, we should try to stick to their conventions as much as possible, shouldn't we?

**Comment by Toflar** [comment]
Fine for me, as I voted: both ways are shitty and there's no perfect way :(

**Comment by discordier** [comment]
The downside I see with putting the tests below `src` is the autoloader information.

Current way (example):
```json
    "autoload": {
        "psr-4": {
            "Contao\\CoreBundle\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Contao\\CoreBundle\\Tests\\": "tests/"
        }
    },
```

when tests within `/src` (example):
```json
    "autoload": {
        "psr-4": {
            "Contao\\CoreBundle\\": "src/",
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Contao\\CoreBundle\\Tests\\": "src/Tests/"
        }
    },
```
Which will make the classes within tests also available via normal autoloading (as they reside in a sub namespace of the bundle) and therefore rendering the definition of `require-dev` useless.

But I really doubt we want the unit tests and their classes available via autoloading when not installed with `--dev`.

**Comment by aschempp** [comment]
Would that possibly mean the tests are included in the bootstrap class cache?

**Comment by leofeyer** [comment]
Right now we are not even using the `autoload-dev` feature :)

IMHO, what you are saying only matters if you generate a mapper class loader. As long as it is PRS-4, the additional `Tests/` folder adds no overhead at all.

**Comment by discordier** [comment]
Of course it does.
```composer dump-autoload -o```
There you go.
Even the current setting of the PSR-4 Autoloader will allow to load the classes from `Test` subnamespace as it is in the correct hierarchy. That is what I wanted to point out above, by moving the tests in src all classes are reachable via the normal autoloader.
Can we live with the fact that everything from the tests namespace is autoloadable and contained in the class map (optimized autoloader) in prod environments or do we rather not want to have this?

IMO we definately do not want this.

**Comment by aschempp** [comment]
It would not be nice, but it wouldn't really harm the installation, as long as the fixtures are not loaded. Has anyone tried what the class map for Symfony looks like, if they include tests? I quickly googled but there seems no option to exclude certain folders for the class loader.

**Comment by Toflar** [comment]
https://getcomposer.org/doc/04-schema.md#autoload-dev

However, this does not work if all classes are in `src` obviously :(

**Comment by leofeyer** [comment]
> Of course it does.
> ```composer dump-autoload -o```

Oh come on, that's ridiculous. I wrote **unless you generate a mapper class loader** above and that's exactly what `composer dump-autoload -o` does.

By the way, following your argumentation there should not be a `src/Resources/` folder, either, because the PRS-4 autoloader will iterate over it as well. However, this does not seem to be a problem for Symfony, either.

Why are we discussing this? We are already following the [Symfony best practices](http://symfony.com/doc/current/cookbook/bundles/best_practices.html) everywhere, so why not regarding the bundle structure?

**Comment by Toflar** [comment]
> Oh come on, that's ridiculous. I wrote unless you generate a mapper class loader above and that's exactly what composer dump-autoload -o does.

And what you should do in production mode :-) So that's a valid point :-) But anyway, Symfony does have that issue too and they will certainly discuss that as well. Maybe the Jordi and Nils are going to introduce some exclude feature in composer as they are contributors to SF2 as well. Let's follow the SF2 way then, even though I don't like it.

**Comment by leofeyer** [comment]
> And what you should do in production mode :-) So that's a valid point :-)

Yes, but as I also wrote above **this does not seem to be a problem for Symfony, either**.

**Comment by aschempp** [comment]
It's not a problem, but its a performance penalty. There's (currently) not other way for them, but still a valid point for us to consider. I'm still :+1: for merging. I think `Resources/contao` does make total sense as we call it `ResourceProvider::getContaoResources`

**Comment by aschempp** [comment]
Oh @leofeyer I'd love to update the `ResourcesProvider` after you merged everything.

**Comment by leofeyer** [comment]
> There's (currently) not other way for them

That's wrong. There might be no better way for Symfony itself, since they are using the centralized repo with the subtree splits. But I quoted the official best practices for bundles, which means additional bundles. And those could have a separate `test/` folder without any problem.

But here's a compromise: Why don't we start by moving the `contao/` folder to `src/Resources/`, which seems to be fine for all of us? The @aschempp can start adjusting the `ResourcesProvider`.

The tests can stay as is are until next Wednesday :)

**Comment by aschempp** [comment]
> But here's a compromise: Why don't we start by moving the contao/ folder to src/Resources/, which seems to be fine for all of us? The @aschempp can start adjusting the ResourcesProvider.

:+1:

**Comment by leofeyer** [comment]
@aschempp Done. You can start working :)

**Comment by aschempp** [comment]
Already on it! But it takes time as I found out the ResourceProvider was all wrong ^^

Hope to have something by sunday evening.

**Comment by leofeyer** [comment]
> But it takes time as I found out the ResourceProvider was all wrong ^^

LOL

**Comment by aschempp** [comment]
Just noticed, if we have separate repositories, will that still work with (the current) Transifex?

**Comment by leofeyer** [comment]
Yes. In fact it will work much better than with one central repo.
