### ISSUE TITLE
Can we use fabbot.io?

### ISSUE THREAD

**Issue by aschempp** [contao/symfony-todo#7]
As this issue is not related to a specific bundle, I'm creating it here…

http://fabbot.io

Would that be useful to us? I would think so…

**Comment by leofeyer** [comment]
Me too, although I have not used the service before. Can I see it in action somewhere?

**Comment by aschempp** [comment]
Here's an example: http://fabbot.io/report/symfony/symfony/14052/462c3a5d16007e0d1da7a6b2bb0fbcdcb1efb1f7

**Comment by discordier** [comment]
Dauertot....?

**Comment by leofeyer** [comment]
I have authorized the application. Let's see what happens :)
